import java.io.IOException;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.util.Random;

public class RandomGen implements Runnable {

	private PipedOutputStream posEven;
	private PipedOutputStream posOdd;

	public PipedOutputStream getPosEven() {
		return posEven;
	}
	
	public PipedOutputStream getPosOdd() {
		return posOdd;
	}

	public RandomGen() {
		this.posEven = new PipedOutputStream();
		this.posOdd = new PipedOutputStream();
	}

	public void run() {
		System.out.println("Random values generated by first thread:");
		for (int i = 0; i < 10; i++) {
			Random r = new Random();
			int num = r.nextInt(100) + 1;
			try {
				posEven.write(num);
				posOdd.write(num);
			} catch (IOException e) {
				e.printStackTrace();
			}
			System.out.println(num);
		}
	}

}
